### ISSUE TITLE
【已解决】无法显示图片

### ISSUE THREAD

**Issue by fsnhljz** [eallion/memos.top#17]
之前正常显示的，更新了以后就不能显示图片了。

https://hillboy.org/memos/

**Comment by fsnhljz** [comment]
我看了一下，发觉是图片链接少了“/”就是域名之后o/r前面少了斜杠，请问怎么解决呢？

**Comment by fsnhljz** [comment]
main.js文件，252行，少了斜杠，加上就可以了

**Comment by eallion** [comment]
Thanks!
