### ISSUE TITLE
图片显示太小，铺不满

### ISSUE THREAD

**Issue by afycn** [eallion/memos.top#19]
![IMG_2041](https://github.com/eallion/memos.top/assets/43784195/1d539cb7-17a1-4b5e-9a98-98d4b995a9aa)

**Comment by rcy1314** [comment]
对于一些附件，分辨率过大会造成附件容量占比过高，推荐只显示压缩或缩小分辨率的一些上传后的附件图，代码中使用style="flex: 1 1 calc(33.33% - 10px) 会压缩一些，但铺满效果并不好，反而小图会显示更快和完整
<img width="1177" alt="1728159603086" src="https://github.com/user-attachments/assets/208688f1-8eb6-4d13-802f-5bf6a157944c">
