### ISSUE TITLE
新版似乎不支持图片

### ISSUE THREAD

**Issue by Lishuhao-lucky** [eallion/memos.top#21]
![图片](https://github.com/user-attachments/assets/8b69491f-05e9-4bba-919a-8e314e2bfcb5)
原始memos
![图片](https://github.com/user-attachments/assets/f2a9c6b1-27fe-4e8b-bbfa-39813e0bebbc)
渲染结果
我试着使用chatGPT修改main.js，但是由于我不会JavaScript，多番咨询和测试后也没有成功；
测试环境memos服务V0.22.4，个人demo：[https://memos.lishihao.top:9999/](https://memos.lishihao.top:9999/)
index.html中配置：
 ```
 host: 'https://memos.lishihao.top:9999/',  // Your Memos instance.
 limit: '10',  // Pagination to show.
creatorId: '4',  // The old instance is 101, and the new instance is 1. 
domId: '#memos',  // Default #memos.
language: 'zh-CN', // 'en' 'zh-CN' etc. Used by Relative Time.
APIVersion: 'new', // 'new' or 'legacy', Memos API Version, <v0.22.0: 'legacy', >=v0.22.0: 'new'.
total: true, // Display total memos. No interface is displayed in the new version.
```

**Comment by eallion** [comment]
有这种可能，因为新版的资源路径有变化。
你的图片是通过图床引用？还是通过 Memos 上传的呢？如果是后者可能无法渲染出来。

**Comment by Lishuhao-lucky** [comment]
您说的对，我测试了图床引用的图片是可以的；直接通过memos上传的图片无法显示；
![图片](https://github.com/user-attachments/assets/a98f8561-8efe-49d0-b1c1-f4aa8007ef87)
memos图片测试
![图片](https://github.com/user-attachments/assets/6af47769-64ea-45b8-9156-9f3e035d62bb)

**Comment by eallion** [comment]
@Lishuhao-lucky 现在应该支持了。

**Comment by Lishuhao-lucky** [comment]
@eallion 非常棒，然而main.js文件中268和272行的url写绝对了，应该时根据index中设置的url进行引用；我测试了现在的版本，图片加载的链接是您个人的，而不是index中设置的链接；所以我猜需要再更改一下main.js的268行和272行，由于我不会js语法，我就我直接手动改为我自己的url，图片成功加载了
![图片](https://github.com/user-attachments/assets/401106e7-1273-46bf-b124-c07d165ded3a)

**Comment by eallion** [comment]
没注意，现在改了。
